# Generated by Django 3.2.13 on 2022-10-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0006_alter_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
